### ISSUE TITLE
merge inside prismarine-chunk

### ISSUE THREAD

**Issue by rom1504** [mhsjlw/node-mcpe-chunk#2]
should be quite easy once #1 is done.

**Comment by rom1504** [comment]
started at https://github.com/PrismarineJS/prismarine-chunk/pull/21

**Comment by rom1504** [comment]
@mhsjlw Can I add a notice saying to use prismarine-chunk instead in the README of node-mcpe-chunk ? (now that prismarine-chunk support mcpe)

**Comment by mhsjlw** [comment]
@rom1504 yeah, go for it.

**Comment by mhsjlw** [comment]
done. a warning has been posted as well this library is now dead.
